### ISSUE TITLE
AsSpan to save allocations

### ISSUE THREAD

**Issue by furesoft** [MrKWatkins/Ast#28]
For Helper Properties that gives access to specific childs it would be nice to have a span to the Children to have a nice api and don't allocate new arrays

**Comment by MrKWatkins** [comment]
Not following exactly sorry, can you give me an example of what you mean?

**Comment by MrKWatkins** [comment]
I see, something like https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.collectionsmarshal.asspan. Same warnings would apply - if you change the children while still holding the span things could go bad. I might be able to add a typed version too, e.g. AsSpan<NameNode>(), although that wouldn't do any type checks so could go badly wrong.

What's the use case for having an array/span of them by the way? Do you repeatedly iterate the set of names?

**Comment by furesoft** [comment]
No, I only want to reduce allocations or do you suggest storing this kind of children as property instead?

**Comment by MrKWatkins** [comment]
If you just want to iterate once over the Names I'd do something like:

```
public IEnumerable<NamedNode> Names => Children.OfType<NamedNode>();
```

**Comment by furesoft** [comment]
yeah but I have nodes that can be any of the node types

**Comment by MrKWatkins** [comment]
Sorry but I'm still not getting the use case here. Can't you just iterate over Children then? It implements IList<T>. Not getting why you need this separate array to be allocated, or how a span could help instead?
