### ISSUE TITLE
Allow range indexer in Children collection

### ISSUE THREAD

**Issue by furesoft** [MrKWatkins/Ast#29]
Please implement an indexer that accepts a range to select multiple children based on their indices.

sample:
```csharp
var ns = string.Join('.', node.Children[..^1]); // get all children from 0 to children.count-1
```

**Comment by MrKWatkins** [comment]
Done. I've also added EnumerateSlice which would be better for your case as it will avoid an array allocation. E.g.

```
var ns = string.Join('.', node.Children.EnumerateSlice(..^1);
```

There is also an UnsafeSlice if you want to get a ReadOnlySpan of the nodes.

**Comment by furesoft** [comment]
great thanks
